// bookData.js
export const bookData = [
  {
    id: 1,
    name: "Atomic Habits: An Easy & Proven Way to Build Good Habits & Break Bad Ones",
    category: "Self-help",
    author: "James Clear",
    price: 588,
    is_highlighted: true,
    isDiscount: false,
    discount_percentage: 0,
    img: "https://m.media-amazon.com/images/I/91bYsX41DVL.jpg",
    rating: 4.8,
    publisher: "Avery",
    language: "English",
    pages: 320,
  },
  {
    id: 2,
    name: "Stop Letting Everything Affect You",
    category: "Self-help",
    author: "Marc Reklau",
    price: 326,
    is_highlighted: false,
    isDiscount: true,
    discount_percentage: 10,
    img: "https://m.media-amazon.com/images/I/61NfT+7FclL.jpg",
    rating: 4.7,
    publisher: "Independently published",
    language: "English",
    pages: 180,
  },
  {
    id: 3,
    name: "The Let Them Theory",
    category: "Self-help",
    author: "Mel Robbins",
    price: 588,
    is_highlighted: true,
    isDiscount: false,
    discount_percentage: 0,
    img: "https://m.media-amazon.com/images/I/71X8k4m8h3L.jpg",
    rating: 4.6,
    publisher: "Hay House",
    language: "English",
    pages: 256,
  },
  {
    id: 4,
    name: "The Subtle Art of Not Giving a F*ck",
    category: "Self-help",
    author: "Mark Manson",
    price: 457,
    is_highlighted: false,
    isDiscount: true,
    discount_percentage: 15,
    img: "https://m.media-amazon.com/images/I/71QKQ9mwV7L.jpg",
    rating: 4.5,
    publisher: "HarperOne",
    language: "English",
    pages: 224,
  },
  {
    id: 5,
    name: "The Meaning of Your Life",
    category: "Self-help",
    author: "Finding Purpose",
    price: 522,
    is_highlighted: false,
    isDiscount: false,
    discount_percentage: 0,
    img: "https://m.media-amazon.com/images/I/71p-TfR-UvL.jpg",
    rating: 5.0,
    publisher: "Spiritual Press",
    language: "English",
    pages: 310,
  },
  {
    id: 6,
    name: "The Four Agreements: A Practical Guide to Personal Freedom",
    category: "Self-help",
    author: "Don Miguel Ruiz",
    price: 457,
    is_highlighted: true,
    isDiscount: false,
    discount_percentage: 0,
    img: "https://m.media-amazon.com/images/I/716ZAtiZc6L.jpg",
    rating: 4.7,
    publisher: "Amber-Allen Publishing",
    language: "English",
    pages: 160,
  },
  {
    id: 7,
    name: "Lonesome Dove: A Novel",
    category: "History",
    author: "Larry McMurtry",
    price: 555,
    is_highlighted: true,
    isDiscount: false,
    discount_percentage: 0,
    img: "https://m.media-amazon.com/images/I/81RAtiU6Y7L.jpg",
    rating: 4.8,
    publisher: "Simon & Schuster",
    language: "English",
    pages: 843,
  },
  {
    id: 8,
    name: "Pathogenesis: A History of the World in Eight Plagues",
    category: "History",
    author: "Jonathan Kennedy",
    price: 65,
    is_highlighted: false,
    isDiscount: true,
    discount_percentage: 5,
    img: "https://m.media-amazon.com/images/I/71-C4G6LIdL.jpg",
    rating: 4.2,
    publisher: "Crown",
    language: "English",
    pages: 400,
  },
  {
    id: 9,
    name: "1929: Inside the Greatest Crash in Wall Street History",
    category: "History",
    author: "William K. Klingaman",
    price: 620,
    is_highlighted: false,
    isDiscount: false,
    discount_percentage: 0,
    img: "https://m.media-amazon.com/images/I/71XGZ5B4PBL.jpg",
    rating: 4.6,
    publisher: "Harper Perennial",
    language: "English",
    pages: 480,
  },
  {
    id: 10,
    name: "Sapiens: A Brief History of Humankind",
    category: "History",
    author: "Yuval Noah Harari",
    price: 490,
    is_highlighted: true,
    isDiscount: false,
    discount_percentage: 0,
    img: "https://m.media-amazon.com/images/I/713jIoMO3UL.jpg",
    rating: 4.6,
    publisher: "Harper",
    language: "English",
    pages: 443,
  },
  {
    id: 11,
    name: "Homo Deus: A Brief History of Tomorrow",
    category: "History",
    author: "Yuval Noah Harari",
    price: 506,
    is_highlighted: false,
    isDiscount: false,
    discount_percentage: 0,
    img: "https://m.media-amazon.com/images/I/71XG-qC252L.jpg",
    rating: 4.5,
    publisher: "Harper",
    language: "English",
    pages: 464,
  },
  {
    id: 12,
    name: "Nexus: A Brief History of Information Networks",
    category: "History",
    author: "Yuval Noah Harari",
    price: 490,
    is_highlighted: true,
    isDiscount: false,
    discount_percentage: 0,
    img: "https://m.media-amazon.com/images/I/71F1E8S5LIL.jpg",
    rating: 4.6,
    publisher: "Penguin",
    language: "English",
    pages: 512,
  },
  {
    id: 13,
    name: "Grumpy Monkey",
    category: "Children",
    author: "Suzanne Lang",
    price: 65,
    is_highlighted: false,
    isDiscount: false,
    discount_percentage: 0,
    img: "https://m.media-amazon.com/images/I/81S88m9m70L.jpg",
    rating: 4.8,
    publisher: "Random House Studio",
    language: "English",
    pages: 32,
  },
  {
    id: 14,
    name: "See You Later, Alligator",
    category: "Children",
    author: "Sally Hopgood",
    price: 359,
    is_highlighted: false,
    isDiscount: false,
    discount_percentage: 0,
    img: "https://m.media-amazon.com/images/I/81uF+N9Y1ML.jpg",
    rating: 4.8,
    publisher: "Sky Pony",
    language: "English",
    pages: 32,
  },
  {
    id: 15,
    name: "There's a Bear on My Chair",
    category: "Children",
    author: "Ross Collins",
    price: 1833,
    is_highlighted: false,
    isDiscount: true,
    discount_percentage: 5,
    img: "https://m.media-amazon.com/images/I/71S-A7q0qWL.jpg",
    rating: 4.8,
    publisher: "Nosy Crow",
    language: "English",
    pages: 32,
  },
  {
    id: 16,
    name: "Giraffes Can't Dance",
    category: "Children",
    author: "Giles Andreae",
    price: 269,
    is_highlighted: false,
    isDiscount: false,
    discount_percentage: 0,
    img: "https://m.media-amazon.com/images/I/819m8V-BqUL.jpg",
    rating: 4.8,
    publisher: "Cartwheel Books",
    language: "English",
    pages: 32,
  },
  {
    id: 17,
    name: "Llama Llama Red Pajama",
    category: "Children",
    author: "Anna Dewdney",
    price: 163,
    is_highlighted: false,
    isDiscount: false,
    discount_percentage: 0,
    img: "https://m.media-amazon.com/images/I/81R6-h90pFL.jpg",
    rating: 4.8,
    publisher: "Viking Books for Young Readers",
    language: "English",
    pages: 40,
  },
  {
    id: 18,
    name: "Chicka Chicka Boom Boom",
    category: "Children",
    author: "Bill Martin Jr.",
    price: 261,
    is_highlighted: false,
    isDiscount: false,
    discount_percentage: 0,
    img: "https://m.media-amazon.com/images/I/81pIn2JtYAL.jpg",
    rating: 4.9,
    publisher: "Little Simon",
    language: "English",
    pages: 36,
  },
  {
    id: 19,
    name: "The Night We Met",
    category: "Romance",
    author: "Zoë Folbigg",
    price: 490.05,
    is_highlighted: true,
    isDiscount: true,
    discount_percentage: 20,
    img: "https://m.media-amazon.com/images/I/81mXpS+X6vL.jpg",
    rating: 4.5,
    publisher: "Aria",
    language: "English",
    pages: 368,
  },
  {
    id: 20,
    name: "In the Great Quiet: A Novel",
    category: "Romance",
    author: "Laura Vogt",
    price: 130.44,
    is_highlighted: false,
    isDiscount: false,
    discount_percentage: 0,
    img: "https://m.media-amazon.com/images/I/71M7-N-7vOL.jpg",
    rating: 4.2,
    publisher: "St. Martin's Press",
    language: "English",
    pages: 320,
  },
  {
    id: 21,
    name: "Hunt the Villain: A Dark MM College Mafia Romance",
    category: "Romance",
    author: "S.J. Sylvis",
    price: 195.85,
    is_highlighted: false,
    isDiscount: true,
    discount_percentage: 10,
    img: "https://m.media-amazon.com/images/I/71R-W-0vL.jpg",
    rating: 4.8,
    publisher: "Self-published",
    language: "English",
    pages: 420,
  },
  {
    id: 22,
    name: "In Her Own League: A Windy City Series Spinoff",
    category: "Romance",
    author: "Liz Tomforde",
    price: 195.53,
    is_highlighted: true,
    isDiscount: false,
    discount_percentage: 0,
    img: "https://m.media-amazon.com/images/I/71E-I-0vL.jpg",
    rating: 4.6,
    publisher: "Liz Tomforde",
    language: "English",
    pages: 450,
  },
  {
    id: 23,
    name: "Mistakes Were Made: Story Lake, Book 2",
    category: "Romance",
    author: "Meryl Wilsner",
    price: 195.83,
    is_highlighted: false,
    isDiscount: false,
    discount_percentage: 0,
    img: "https://m.media-amazon.com/images/I/71S-T-0vL.jpg",
    rating: 4.6,
    publisher: "St. Martin's Griffin",
    language: "English",
    pages: 384,
  },
  {
    id: 24,
    name: "A Court of Thorns and Roses 6",
    category: "Romance",
    author: "Sarah J. Maas",
    price: 300.11,
    is_highlighted: true,
    isDiscount: false,
    discount_percentage: 0,
    img: "https://m.media-amazon.com/images/I/81A-T-0vL.jpg",
    rating: 4.8,
    publisher: "Bloomsbury Publishing",
    language: "English",
    pages: 500,
  },
  {
    id: 25,
    name: "Project Hail Mary",
    category: "Science fiction & Fantasy",
    author: "Andy Weir",
    price: 490.05,
    is_highlighted: true,
    isDiscount: false,
    discount_percentage: 0,
    img: "https://m.media-amazon.com/images/I/81A7879H7yL.jpg",
    rating: 4.7,
    publisher: "Ballantine Books",
    language: "English",
    pages: 476,
  },
  {
    id: 26,
    name: "Dungeon Crawler Carl",
    category: "Science fiction & Fantasy",
    author: "Matt Dinniman",
    price: 163.13,
    is_highlighted: false,
    isDiscount: true,
    discount_percentage: 10,
    img: "https://m.media-amazon.com/images/I/81p-T-0vL.jpg",
    rating: 4.7,
    publisher: "Matt Dinniman",
    language: "English",
    pages: 400,
  },
  {
    id: 27,
    name: "Harry Potter and the Sorcerer's Stone",
    category: "Science fiction & Fantasy",
    author: "J.K. Rowling",
    price: 391.98,
    is_highlighted: true,
    isDiscount: false,
    discount_percentage: 0,
    img: "https://m.media-amazon.com/images/I/81S-T-0vL.jpg",
    rating: 4.8,
    publisher: "Scholastic",
    language: "English",
    pages: 309,
  },
  {
    id: 28,
    name: "Harry Potter and the Goblet of Fire",
    category: "Science fiction & Fantasy",
    author: "J.K. Rowling",
    price: 391.98,
    is_highlighted: false,
    isDiscount: false,
    discount_percentage: 0,
    img: "https://m.media-amazon.com/images/I/81S-T-0vL.jpg",
    rating: 4.8,
    publisher: "Scholastic",
    language: "English",
    pages: 734,
  }
];